apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-

spec:
  entrypoint: echo-alphabet
  artifacts:
    base: s3://argo-minio/artifacts/2017/10/20

  templates:
  - name: echo
    type: container
    inputs:
      parameters:
        MESSAGE:
    image: alpine:latest
    command: [sh, -c]
    args: ["echo %%inputs.parameters.MESSAGE%%; echo done"]
  - name: hello
    type: workflow
    steps:
    - ECHO-D:
        template: echo
        arguments:
          parameters.MESSAGE: "D"
  - name: echo-alphabet
    type: workflow
    steps:
    - ECHO-A:
        template: echo
        arguments:
          parameters.MESSAGE: "a"
      ECHO-B:
        template: echo
        arguments:
          parameters.MESSAGE: "b"
    - ECHO-C:
        template: echo
        arguments:
          parameters.MESSAGE: "c"
      ECHO-D-WF:
        template: hello
    - ECHO-E:
        template: echo
        arguments:
          parameters.MESSAGE: "e"
