apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
templates:
- name: echo
  type: container
  inputs:
    parameters:
      MESSAGE:
  image: alpine:latest
  command: [sh, -c]
  args: ["echo %%inputs.parameters.MESSAGE%%; sleep 30; echo done"]
- name: echo-alphabet
  type: workflow
  steps:
  - ECHO-A:
      template: echo
      arguments:
        parameters.MESSAGE: "a"
    ECHO-B:
      template: echo
      arguments:
        parameters.MESSAGE: "b"
  - ECHO-C:
      template: echo
      arguments:
        parameters.MESSAGE: "c"
target: echo-alphabet
