[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/apiextensions-apiserver"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-5.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
