apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: workflow-controller-deployment
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - name: workflow-controller
        image: argoproj/workflow-controller:latest
        command: [/bin/workflow-controller]
        args: [--configmap, workflow-controller-configmap]
