apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
spec:
  entrypoint: artifact-argument-example
  arguments:
    artifacts:
    - name: CODE
      http:
        url: https://mycompany.com/files/foo

  templates:
  - name: artifact-argument-example
    inputs:
      artifacts:
      - name: CODE
        path: /src
    container:
      image: debian:latest
      command: [sh, -c]
      args: ["cd /src && ls -l"]
