apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
spec:
  entrypoint: cowsay
  arguments:
    parameters:
    - name: MESSAGE
      value: hello world

  templates:
  - name: cowsay
    inputs:
      parameters:
      - name: MESSAGE
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.MESSAGE}}"]
