apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: ci-example-
spec:
  entrypoint: ci-example
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  templates:
  - name: ci-example
    steps:
    - - name: build
        template: build-golang-example
    - - name: test
        template: run-hello

  - name: build-golang-example
    inputs:
      artifacts:
      - name: CODE
        path: /go/src/github.com/golang/example
        git:
          repo: https://github.com/golang/example.git
    container:
      image: golang:1.8
      command: [sh, -c]
      args: ["
        cd /go/src/github.com/golang/example/hello &&
        go build -v .
      "]
      volumeMounts:
      - name: workdir
        mountPath: /go

  - name: run-hello
    container:
      image: debian:9.1
      command: [sh, -c]
      args: ["/go/src/github.com/golang/example/hello/hello"]
      volumeMounts:
      - name: workdir
        mountPath: /go
