apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
spec:
  entrypoint: conditional-example
  arguments:
    parameters.DO-PRINT: "false"
  templates:
  - name: conditional-example
    inputs:
      parameters:
        DO-PRINT:
    steps:
    - PRINT-HELLO:
        template: cowsay
        when: "{{inputs.parameters.DO-PRINT}} == true"

  - name: cowsay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello"]
