apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
spec:
  entrypoint: cowsay
  templates:
  - name: cowsay
    type: container
    image: docker/whalesay:latest
    command: [cowsay]
    args: ["hello world"]
