# Example of using a hard-wired artifact location
apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
spec:
  entrypoint: http-artifact-example
  templates:
  - name: http-artifact-example
    inputs:
      artifacts:
      - name: CODE
        path: /bin/foo
        http:
          url: https://mycompany.com/files/foo
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["/bin/foo"]
