apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
spec:
  entrypoint: git-clone
  templates:
  - name: git-clone
    inputs:
      artifacts:
        CODE:
          path: /src
          git:
            url: https://github.com/argoproj/argo.git
    container:
      image: golang:1.8
      command: [sh, -c]
      args: ["cd /src; git status"]
