apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
spec:
  entrypoint: http-artifact-example
  templates:
  - name: http-artifact-example
    type: container
    inputs:
      artifacts:
        CODE:
          path: /bin/foo
          http:
            url: https://mycompany.com/files/foo
    image: alpine:latest
    command: [sh, -c]
    args: ["/bin/foo"]
