apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
spec:
  entrypoint: cowsay
  arguments:
    parameters.MESSAGE: "hello world"
  templates:
  - name: cowsay
    type: container
    inputs:
      parameters:
        MESSAGE:
    image: docker/whalesay:latest
    command: [cowsay]
    args: ["{{inputs.parameters.MESSAGE}}"]
