apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
spec:
  entrypoint: loop-map-example
  templates:
  - name: loop-map-example
    steps:
    - PRINT-OS:
        template: cat-os-release
        arguments:
          parameters.IMAGE: "{{item.image}}"
          parameters.TAG: "{{item.tag}}"
        withItems:
        - { image: 'debian', tag: '9.1' }
        - { image: 'debian', tag: '8.9' }
        - { image: 'alpine', tag: '3.6' }

  - name: cat-os-release
    inputs:
      parameters:
        IMAGE:
        TAG:
    container:
      image: "{{inputs.parameters.IMAGE}}:{{inputs.parameters.TAG}}"
      command: [cat]
      args: [/etc/os-release]
