apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
spec:
  entrypoint: loop-example
  templates:
  - 
    name: loop-example
    steps:
    - COWSAY:
        template: cowsay
        arguments:
          parameters.MESSAGE: "{{item}}"
        withItems:
        - hello world
        - goodbye world
  - 
    name: cowsay
    inputs:
      parameters:
        MESSAGE:
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.MESSAGE}}"]
