apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: argo-wf-
spec:
  entrypoint: loop-example
  templates:
  - name: loop-example
    steps:
    - COWSAY:
        template: cowsay
        arguments:
          parameters:
          - name: MESSAGE
            value: "{{item}}"
        withItems:
        - hello world
        - goodbye world

  - name: cowsay
    inputs:
      parameters:
      - name: MESSAGE
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.MESSAGE}}"]
