apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nested-workflow-
spec:
  entrypoint: nested-workflow-example
  templates:
  - name: nested-workflow-example
    steps:
    - - name: generate
        template: whalesay
    - - name: nested
        template: nested-wf
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate.outputs.artifacts.hello-artifact}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-artifact
        path: /tmp/hello_world.txt

  - name: nested-wf
    inputs:
      artifacts:
      - name: message
    steps:
    - - name: print
        template: print-message
        arguments:
          artifacts:
          - name: message2
            from: "{{inputs.artifacts.message}}"

  - name: print-message
    inputs:
      artifacts:
      - name: message2
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
